include: package:lints/recommended.yaml

analyzer:
  exclude:
    - grammars/**
    - tree-sitter/**
    - build/**
    - output/**
    - .cache/**
    - test/highlights/**

linter:
  rules:
    avoid_print: false
