name: tree_sitter_grammars
description: Pre-built tree-sitter grammar libraries and query files for syntax highlighting.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  ffi: ^2.2.0
  path: ^1.9.0

dev_dependencies:
  checks: ^0.3.2
  lints: ^5.0.0
  test: ^1.32.0
