/// Builds the tree-sitter runtime, every pinned grammar and their query
/// bundles into `output/`.
///
/// Usage:
///
/// ```sh
/// dart run tool/build_tree_sitter_grammars.dart
/// dart run tool/build_tree_sitter_grammars.dart --release=vX.Y.Z [--dry-run]
/// ```
///
/// Every build starts from empty `build/` and `output/` directories. The
/// runtime and each grammar are extracted with `git archive` at the commit
/// `tool/toolchain.json` and `tool/grammars.json` pin; `grammars/<repo>`
/// serves only as a git object store and its working tree is never read.
/// A grammar that commits no `parser.c` is generated by the pinned CLI.
/// Every library is compiled by Xcode's clang with the flags in
/// `tool/src/compiler.dart`, and `output/build_info.json` records them.
///
/// `--release=vX.Y.Z` first requires a clean working tree whose `HEAD` is
/// the annotated tag `vX.Y.Z`, and then packs `output/` into
/// `output/grammars-macos-arm64.tar.gz`. `--dry-run` skips only the tag
/// requirement and packs the same bytes into
/// `output/grammars-macos-arm64.dry-run.tar.gz`, a name no release asset
/// has.
///
/// The build writes into `build/out/` and moves it to `output/` only after
/// every check passes, so a failed build leaves no `output/`. Any failure
/// exits non-zero before anything is packed.
library;

import 'dart:io';
import 'dart:math';

import 'package:path/path.dart' as p;

import 'src/build_record.dart';
import 'src/compiler.dart';
import 'src/git.dart';
import 'src/grammar_pins.dart';
import 'src/grammar_plan.dart';
import 'src/grammar_sources.dart';
import 'src/macho.dart';
import 'src/manifest.dart';
import 'src/query_headers.dart';
import 'src/query_provenance.dart';
import 'src/release.dart';
import 'src/toolchain.dart';
import 'src/tree_sitter_cli.dart';

const _usage =
    'usage: dart run tool/build_tree_sitter_grammars.dart '
    '[--release=vX.Y.Z [--dry-run]]';

/// Thrown to stop the build with a message.
final class BuildException implements Exception {
  const BuildException(this.message);

  final String message;

  @override
  String toString() => message;
}

Future<void> main(List<String> args) async {
  final String? release;
  final bool dryRun;
  switch (args) {
    case []:
      (release, dryRun) = (null, false);
    case [final flag] when flag.startsWith('--release='):
      (release, dryRun) = (flag.substring('--release='.length), false);
    case [final flag, '--dry-run'] when flag.startsWith('--release='):
      (release, dryRun) = (flag.substring('--release='.length), true);
    default:
      stderr.writeln(_usage);
      exit(64);
  }
  if (release != null && !RegExp(r'^v\d+\.\d+\.\d+$').hasMatch(release)) {
    stderr.writeln('--release takes a tag of the form vX.Y.Z, not $release');
    exit(64);
  }
  final root = p.dirname(p.dirname(p.fromUri(Platform.script)));
  try {
    await _build(root, release: release, dryRun: dryRun);
  } on Exception catch (error) {
    stderr.writeln('\n✗ $error');
    exit(1);
  }
}

Future<void> _build(
  String root, {
  required String? release,
  required bool dryRun,
}) async {
  // output/ holds only a build that passed every check: it is removed
  // before anything can fail, and the build fills build/out/ and moves it
  // into place last.
  _delete(p.join(root, 'output'));
  final toolchain = Toolchain.load(root);
  final entries = parseGrammars(
    File(p.join(root, 'tool', 'grammars.json')).readAsStringSync(),
  );
  _step('Checking pins, query provenance and the runtime submodule');
  _requireNone('grammars.json', pinProblems(entries));
  _requireNone('query_provenance.json', _provenanceProblems(root, entries));
  await _requireRuntimeSubmodule(root, toolchain);
  if (release != null) {
    await checkReleasePreflight(
      runGit,
      root,
      release,
      runtimeCommit: toolchain.treeSitterCommit,
      dryRun: dryRun,
    );
    if (dryRun) print('  --dry-run: not requiring HEAD to be the tag $release');
  }

  _delete(p.join(root, 'build'));

  _step(
    'Extracting the runtime and ${_urlEntries(entries).length} grammar '
    'repositories at their pins',
  );
  final runtimeDirectory = p.join(root, 'build', 'src', 'tree-sitter');
  await extractCommit(
    p.join(root, 'tree-sitter'),
    toolchain.treeSitterCommit,
    runtimeDirectory,
  );
  final languageVersions = _runtimeLanguageVersions(
    runtimeDirectory,
    toolchain,
  );
  await _extractGrammars(root, entries);

  final builds = planGrammars(root, entries);
  for (final build in builds) {
    checkSources(root, build);
  }
  final generated = builds.where((build) => build.generate).toList();
  if (generated.isNotEmpty) {
    _step(
      'Generating ${generated.map((b) => b.name).join(', ')} with '
      'tree-sitter ${toolchain.cliVersion}',
    );
    final cli = await ensureCli(root, toolchain);
    for (final build in generated) {
      await generateParser(
        cli: cli,
        grammarDirectory: p.join(root, p.dirname(build.sourceDirectory)),
        outputDirectory: p.join(root, build.generatedDirectory),
        abi: languageVersions.current,
      );
    }
  }

  _step('Compiling the runtime and ${builds.length} grammars');
  final compiler = await Compiler.resolve();
  final flags = BuildFlags(toolchain, compiler);
  final environment = compilerEnvironment(Platform.environment);
  print(
    '  ${compiler.version}\n  ${compiler.path}\n'
    '  SDK ${compiler.sdkVersion} (${compiler.sdkBuildVersion})',
  );
  final outputDirectory = p.join(root, 'build', 'out');
  final runtime = runtimeCommand(
    compiler: compiler,
    flags: flags,
    directory: runtimeDirectory,
    output: p.relative(
      p.join(outputDirectory, 'libtree-sitter.dylib'),
      from: runtimeDirectory,
    ),
    environment: environment,
  );
  final grammarCommands = [
    for (final build in builds)
      _grammarCommands(root, build, compiler, flags, environment),
  ];
  final commands = [runtime, for (final group in grammarCommands) ...group];
  File(
    p.join(root, 'build', 'compile_commands.json'),
  ).writeAsStringSync(encodeCompileCommands(commands));
  Directory(p.join(outputDirectory, 'dylibs')).createSync(recursive: true);
  for (final build in builds) {
    Directory(p.join(root, build.objectDirectory)).createSync(recursive: true);
    Directory(
      p.join(outputDirectory, build.dylibDirectory),
    ).createSync(recursive: true);
  }
  _requireNone(
    'compile',
    [
      ...await _pooled([runtime], _run),
      ...await _pooled(grammarCommands, _runInOrder),
    ].nonNulls.toList(),
  );

  _step('Checking every library');
  final expectations = [
    LibraryExpectation(
      path: p.join(outputDirectory, 'libtree-sitter.dylib'),
      installName: '@rpath/libtree-sitter.dylib',
      exportedSymbols: const ['_ts_parser_new', '_ts_language_abi_version'],
    ),
    for (final build in builds)
      LibraryExpectation(
        path: p.join(
          outputDirectory,
          build.dylibDirectory,
          build.dylibFileName,
        ),
        installName: '@rpath/${build.dylibFileName}',
        exportedSymbols: ['_tree_sitter_${build.symbol}'],
      ),
  ];
  _requireNone('libraries', [
    for (final problems in await _pooled(
      expectations,
      (e) => libraryProblems(e, toolchain),
    ))
      ...problems,
  ]);

  _step('Writing query bundles, manifest.json and build_info.json');
  final manifest = _writeBundles(root, outputDirectory, entries, builds);
  File(
    p.join(outputDirectory, 'manifest.json'),
  ).writeAsStringSync(encodeManifest(manifest));
  final info = buildInfo(
    release: release,
    toolchain: toolchain,
    compiler: compiler,
    flags: flags,
    repositoryCommit: (await runGit(root, ['rev-parse', 'HEAD'])).trim(),
    repositoryDirty: (await runGit(root, [
      'status',
      '--porcelain',
    ])).trim().isNotEmpty,
    languageVersion: languageVersions.current,
    minCompatibleLanguageVersion: languageVersions.minCompatible,
  );
  File(
    p.join(outputDirectory, 'build_info.json'),
  ).writeAsStringSync(encodeBuildInfo(info));

  _step('Checking the recorded flags and the manifest');
  await _checkRecords(root, outputDirectory, builds);
  final output = Directory(outputDirectory).renameSync(p.join(root, 'output'));

  print(
    '\n✓ Built libtree-sitter.dylib, ${builds.length} grammar dylibs and '
    '${manifest.values.where((e) => e['queryOnly'] == true).length} '
    'query-only bundles into output/',
  );
  if (release != null) {
    _step('Packing $release${dryRun ? ' (dry run)' : ''}');
    print('  ${await _createReleaseArchive(output.path, dryRun: dryRun)}');
  }
}

void _step(String title) => print('\n── $title');

void _delete(String path) {
  if (Directory(path).existsSync()) Directory(path).deleteSync(recursive: true);
}

void _requireNone(String what, List<String> problems) {
  if (problems.isEmpty) return;
  throw BuildException(['$what:', ...problems].join('\n  '));
}

Iterable<Map<String, Object?>> _urlEntries(
  List<Map<String, Object?>> entries,
) => entries.where((entry) => entry['url'] is String);

/// Every problem with `tool/query_provenance.json` and with the header each
/// query file derived from nvim-treesitter carries.
List<String> _provenanceProblems(
  String root,
  List<Map<String, Object?>> entries,
) {
  final queryFiles = [
    for (final entity in Directory(
      p.join(root, 'queries'),
    ).listSync(recursive: true))
      if (entity is File && entity.path.endsWith('.scm'))
        p.posix.joinAll(p.split(p.relative(entity.path, from: root))),
  ];
  final json = File(
    p.join(root, 'tool', 'query_provenance.json'),
  ).readAsStringSync();
  final reading = readQueryProvenance(json, queryFiles);
  if (reading.problems.isNotEmpty) return reading.problems;
  return queryHeaderCheck(root, reading.entries, licenseLookup(entries));
}

/// Requires the `tree-sitter` submodule's checkout to be the toolchain's
/// commit.
Future<void> _requireRuntimeSubmodule(String root, Toolchain toolchain) async {
  final head = (await runGit(p.join(root, 'tree-sitter'), [
    'rev-parse',
    'HEAD',
  ])).trim();
  if (head != toolchain.treeSitterCommit) {
    throw BuildException(
      'tree-sitter is checked out at $head; '
      'toolchain.json pins ${toolchain.treeSitterTag} '
      '(${toolchain.treeSitterCommit})',
    );
  }
}

/// The runtime's `TREE_SITTER_LANGUAGE_VERSION` and
/// `TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION`, after checking that its
/// Makefile declares the toolchain's version.
({int current, int minCompatible}) _runtimeLanguageVersions(
  String runtimeDirectory,
  Toolchain toolchain,
) {
  final makefile = File(
    p.join(runtimeDirectory, 'Makefile'),
  ).readAsStringSync();
  final version = RegExp(
    r'^VERSION := (\S+)$',
    multiLine: true,
  ).firstMatch(makefile)?.group(1);
  if (version != toolchain.runtimeVersion) {
    throw BuildException(
      'the runtime Makefile declares VERSION $version, '
      'toolchain.json says ${toolchain.runtimeVersion}',
    );
  }
  final api = File(
    p.join(runtimeDirectory, 'lib', 'include', 'tree_sitter', 'api.h'),
  ).readAsStringSync();
  int define(String name) {
    final match = RegExp(
      '^#define $name (\\d+)\$',
      multiLine: true,
    ).firstMatch(api);
    if (match == null) throw BuildException('api.h does not define $name');
    return int.parse(match.group(1)!);
  }

  return (
    current: define('TREE_SITTER_LANGUAGE_VERSION'),
    minCompatible: define('TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION'),
  );
}

Future<void> _extractGrammars(
  String root,
  List<Map<String, Object?>> entries,
) async {
  final problems = await _pooled(_urlEntries(entries).toList(), (entry) async {
    final url = entry['url']! as String;
    final commit = entry['commit']! as String;
    final name = repositoryName(url);
    final store = p.join(root, 'grammars', name);
    try {
      await ensureObjectStore(runGit, store, url);
      await ensureCommit(runGit, store, commit, name);
      await extractCommit(store, commit, p.join(root, 'build', 'src', name));
      return null;
    } on Exception catch (error) {
      return '$name: $error';
    }
  }, limit: 8);
  _requireNone('extract', problems.nonNulls.toList());
}

/// The compile of each of [build]'s sources, then its link, in order.
List<CompileCommand> _grammarCommands(
  String root,
  GrammarBuild build,
  Compiler compiler,
  BuildFlags flags,
  Map<String, String> environment,
) {
  final sources = [
    (build.parserSource, build.parserIncludeDirectory),
    if (scannerSource(root, build) case final scanner?)
      (scanner, scannerIncludeDirectory(root, build)),
  ];
  final compiles = [
    for (final (source, include) in sources)
      grammarCompileCommand(
        compiler: compiler,
        flags: flags,
        directory: root,
        includeDirectory: include,
        source: source,
        object: p.join(
          build.objectDirectory,
          '${p.basenameWithoutExtension(source)}.o',
        ),
        environment: environment,
      ),
  ];
  return [
    ...compiles,
    grammarLinkCommand(
      compiler: compiler,
      flags: flags,
      directory: root,
      libraryName: build.name,
      objects: [for (final compile in compiles) compile.output],
      output: p.join('build', 'out', build.dylibDirectory, build.dylibFileName),
      environment: environment,
    ),
  ];
}

Future<String?> _run(CompileCommand command) async {
  try {
    await runCompileCommand(command);
    return null;
  } on CompilerException catch (error) {
    return error.message;
  }
}

Future<String?> _runInOrder(List<CompileCommand> commands) async {
  for (final command in commands) {
    if (await _run(command) case final problem?) return problem;
  }
  return null;
}

/// Runs [task] over [items] with at most [limit] running at once, and
/// returns the results in the order of [items].
Future<List<R>> _pooled<T, R>(
  List<T> items,
  Future<R> Function(T) task, {
  int? limit,
}) async {
  final results = List<R?>.filled(items.length, null);
  var next = 0;
  Future<void> worker() async {
    while (next < items.length) {
      final index = next++;
      results[index] = await task(items[index]);
    }
  }

  final workers = min(limit ?? Platform.numberOfProcessors, items.length);
  await Future.wait([for (var i = 0; i < workers; i++) worker()]);
  return results.cast<R>();
}

/// Bundles every language's queries into [outputDirectory] and returns the
/// manifest, in `grammars.json` order.
Map<String, Map<String, Object?>> _writeBundles(
  String root,
  String outputDirectory,
  List<Map<String, Object?>> entries,
  List<GrammarBuild> builds,
) {
  final manifest = <String, Map<String, Object?>>{};
  for (final entry in entries) {
    if (entry['noop'] == true) {
      manifest[entry['name']! as String] = noopEntry(entry);
    } else if (entry['queryOnly'] == true) {
      final name = entry['name']! as String;
      final manifestEntry = queryOnlyEntry(entry);
      bundleQueries(
        root,
        name,
        manifestEntry['queries']! as Map<String, Object?>,
        p.join(outputDirectory, 'queries', name),
      );
      manifest[name] = manifestEntry;
    } else {
      for (final build in builds.where((build) => build.entry == entry)) {
        final manifestEntry = grammarEntry(
          root,
          build,
          parserAbi(p.join(root, build.parserSource)),
        );
        bundleQueries(
          root,
          build.name,
          manifestEntry['queries']! as Map<String, Object?>,
          p.join(outputDirectory, build.dylibDirectory),
        );
        manifest[build.name] = manifestEntry;
      }
    }
  }
  return manifest;
}

/// Reads `build_info.json` in [outputDirectory] and
/// `build/compile_commands.json` back from disk and requires every
/// invocation to have passed exactly the recorded flags; then requires
/// `validate_manifest.dart` to pass on [outputDirectory]'s manifest.
Future<void> _checkRecords(
  String root,
  String outputDirectory,
  List<GrammarBuild> builds,
) async {
  final problems = checkRecordedFlags(
    buildInfoPath: p.join(outputDirectory, 'build_info.json'),
    compileCommandsPath: p.join(root, 'build', 'compile_commands.json'),
    grammarNames: {for (final build in builds) build.name},
  );
  _requireNone('recorded flags', problems);
  print('  every compiler invocation passed exactly the recorded flags');
  final validation = await Process.run(Platform.resolvedExecutable, [
    'run',
    p.join('tool', 'validate_manifest.dart'),
    p.join(outputDirectory, 'manifest.json'),
  ], workingDirectory: root);
  if (validation.exitCode != 0) {
    throw BuildException(
      'validate_manifest.dart exited '
      '${validation.exitCode}\n${validation.stdout}${validation.stderr}',
    );
  }
  print('  validate_manifest.dart passed');
}

/// Packs `output/` into [releaseArchiveName], or into [dryRunArchiveName]
/// when [dryRun].
Future<String> _createReleaseArchive(
  String outputDirectory, {
  required bool dryRun,
}) async {
  final archiveName = dryRun ? dryRunArchiveName : releaseArchiveName;
  final result = await Process.run('tar', [
    '-czf',
    archiveName,
    'libtree-sitter.dylib',
    'dylibs',
    'queries',
    'manifest.json',
    'build_info.json',
  ], workingDirectory: outputDirectory);
  if (result.exitCode != 0) {
    throw BuildException('tar failed: ${result.stderr}');
  }
  return p.join(outputDirectory, archiveName);
}
