/// Builds the tree-sitter runtime, every pinned grammar and their query
/// bundles into `output/`.
///
/// Usage:
///
/// ```sh
/// dart run tool/build_tree_sitter_grammars.dart [--sources=<dir>]
/// dart run tool/build_tree_sitter_grammars.dart --release=vX.Y.Z
///     [--dry-run | --publish]
/// ```
///
/// Every build starts from empty `build/` and `output/` directories. The
/// runtime and each grammar come from a source bundle: the tree `git
/// archive` writes at the commit `tool/toolchain.json` and
/// `tool/grammars.json` pin, gzip-compressed, which the build writes to
/// `output/sources/` and compiles from. `tree-sitter/` and
/// `grammars/<repo>` serve only as git object stores; a grammar's working
/// tree is never read. With `--sources=<dir>`, the bundles come from
/// `<dir>` instead, checked against the `build_info.json` beside them, and
/// no object store is read: `<dir>` holds a release's downloaded assets.
/// A grammar whose entry lists `patches` has them applied to its unpacked
/// tree, read from this repository's `patches/`, and the patched files must
/// have the `patchedSha256` the entry records; its bundle stays the tree at
/// the pin.
/// A grammar that commits no `parser.c` is generated by the pinned CLI, and
/// what it generates is packed into `output/sources/` too; with
/// `--sources`, it is taken from `<dir>` instead and no CLI runs. Every
/// tree compiled, generated or not, must have the digest its pin records.
/// Every library is compiled by Xcode's clang with the flags in
/// `tool/src/compiler.dart`, and `output/build_info.json` records them and
/// every bundle's sha256.
///
/// `--release=vX.Y.Z` first requires a clean working tree whose `HEAD` is
/// the annotated tag `vX.Y.Z`, and reads this repository's own files (its
/// pins, query files, provenance and licences) from that commit's tree,
/// extracted into `build/repository`, never from the working tree. It packs
/// `output/` into `output/grammars-macos-arm64.tar.gz` only if `HEAD` is
/// still that commit and the working tree still clean once every check has
/// passed. `--dry-run` skips only the tag requirement and packs the same
/// bytes into
/// `output/grammars-macos-arm64.dry-run.tar.gz`, a name no release asset
/// has. Packing also writes the archive's sha256 beside it and the release
/// notes into `output/release-notes.md`. `--publish` then creates the
/// GitHub release of the pushed tag with the archive, its sha256,
/// `build_info.json` and every source and generated bundle attached; it
/// refuses a release that exists, so an asset is never replaced, and a tag
/// on GitHub that is not the local tag naming the built commit.
///
/// The build writes into `build/out/` and moves it to `output/` only after
/// every check passes, so a failed build leaves no `output/`. Any failure
/// exits non-zero before anything is packed.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'src/build_record.dart';
import 'src/compiler.dart';
import 'src/generated_sources.dart';
import 'src/git.dart';
import 'src/grammar_pins.dart';
import 'src/grammar_plan.dart';
import 'src/grammar_sources.dart';
import 'src/macho.dart';
import 'src/manifest.dart';
import 'src/notices.dart';
import 'src/pool.dart';
import 'src/publish.dart';
import 'src/query_headers.dart';
import 'src/query_provenance.dart';
import 'src/release.dart';
import 'src/release_archive.dart';
import 'src/source_bundles.dart';
import 'src/toolchain.dart';
import 'src/tree_sitter_cli.dart';

const _usage =
    'usage: dart run tool/build_tree_sitter_grammars.dart '
    '[--sources=<dir>] [--release=vX.Y.Z [--dry-run | --publish]]';

/// What the command line asks the build to do.
typedef _Options = ({
  String? release,
  bool dryRun,
  bool publish,
  String? sources,
});

/// Reads [args], or returns null when they are not a command the build
/// takes.
_Options? _parseArguments(List<String> args) {
  String? release;
  String? sources;
  var dryRun = false;
  var publish = false;
  for (final arg in args) {
    if (arg.startsWith('--release=') && release == null) {
      release = arg.substring('--release='.length);
    } else if (arg.startsWith('--sources=') && sources == null) {
      sources = arg.substring('--sources='.length);
    } else if (arg == '--dry-run' && !dryRun) {
      dryRun = true;
    } else if (arg == '--publish' && !publish) {
      publish = true;
    } else {
      return null;
    }
  }
  if ((dryRun || publish) && release == null) return null;
  if (dryRun && publish) return null;
  if (sources != null && sources.isEmpty) return null;
  return (release: release, dryRun: dryRun, publish: publish, sources: sources);
}

/// Thrown to stop the build with a message.
final class BuildException implements Exception {
  const BuildException(this.message);

  final String message;

  @override
  String toString() => message;
}

Future<void> main(List<String> args) async {
  final options = _parseArguments(args);
  if (options == null) {
    stderr.writeln(_usage);
    exit(64);
  }
  final release = options.release;
  if (release != null && !RegExp(r'^v\d+\.\d+\.\d+$').hasMatch(release)) {
    stderr.writeln('--release takes a tag of the form vX.Y.Z, not $release');
    exit(64);
  }
  final root = p.dirname(p.dirname(p.fromUri(Platform.script)));
  try {
    await _build(root, options);
  } on Exception catch (error) {
    stderr.writeln('\n✗ $error');
    exit(1);
  }
}

Future<void> _build(String root, _Options options) async {
  final (:release, :dryRun, :publish, :sources) = options;
  final bundles = sources == null ? null : _sourcesDirectory(root, sources);
  // output/ holds only a build that passed every check: it is removed
  // before anything can fail, and the build fills build/out/ and moves it
  // into place last.
  _delete(p.join(root, 'output'));
  _delete(p.join(root, 'build'));
  final commit = release == null
      ? null
      : await _releaseCommit(root, release, dryRun: dryRun);
  // A release reads this repository's own files from its commit, extracted
  // into build/repository; any other build reads the working tree.
  final inputs = commit == null ? root : await _extractRepository(root, commit);
  final toolchain = Toolchain.load(inputs);
  final entries = parseGrammars(
    File(p.join(inputs, 'tool', 'grammars.json')).readAsStringSync(),
  );
  _step('Checking pins, query provenance and the runtime');
  _requireNone('grammars.json', pinProblems(entries));
  _requireNone('query_provenance.json', _provenanceProblems(inputs, entries));
  if (bundles == null) await _requireRuntimeSubmodule(root, toolchain);
  if (commit != null) {
    await checkRecordedRuntime(
      runGit,
      root,
      commit,
      toolchain.treeSitterCommit,
    );
  }

  final outputDirectory = p.join(root, 'build', 'out');
  final origin = bundles == null
      ? 'from their git object stores'
      : 'from the source bundles in $bundles';
  _step(
    'Unpacking the runtime and ${_urlEntries(entries).length} grammar '
    'repositories at their pins, $origin',
  );
  final sourceRecords = await supplySources(
    root: root,
    toolchain: toolchain,
    entries: entries,
    sourceRoot: p.join(root, 'build', 'src'),
    bundleDirectory: p.join(outputDirectory, sourcesDirectoryName),
    patchRoot: inputs,
    recordedBundles: bundles,
  );
  final runtimeDirectory = p.join(root, 'build', 'src', 'tree-sitter');
  final languageVersions = _runtimeLanguageVersions(
    runtimeDirectory,
    toolchain,
  );

  final builds = planGrammars(root, entries);
  for (final build in builds) {
    checkSources(root, build);
  }

  _step('Writing $noticesFileName');
  _writeNotices(
    inputs,
    outputDirectory,
    NoticesInput(
      toolchain: toolchain,
      runtimeDirectory: runtimeDirectory,
      entries: entries,
      builds: builds,
      sourceRoot: p.join(root, 'build', 'src'),
      provenance: readRepositoryProvenance(inputs),
      apacheLicense: File(
        p.join(inputs, 'LICENSES', 'Apache-2.0.txt'),
      ).readAsStringSync(),
      ownLicense: File(p.join(inputs, 'LICENSE')).readAsStringSync(),
      patchRoot: inputs,
    ),
  );
  final generated = builds.where((build) => build.generate).toList();
  final generatedRecords = bundles == null
      ? await _generate(
          root,
          toolchain,
          generated,
          outputDirectory,
          languageVersions.current,
        )
      : await _takeGenerated(
          root,
          toolchain,
          generated,
          outputDirectory,
          bundles,
        );

  _step('Compiling the runtime and ${builds.length} grammars');
  final compiler = await Compiler.resolve();
  final flags = BuildFlags(toolchain, compiler);
  final environment = compilerEnvironment(Platform.environment);
  print(
    '  ${compiler.version}\n  ${compiler.path}\n'
    '  SDK ${compiler.sdkVersion} (${compiler.sdkBuildVersion})',
  );
  final runtime = runtimeCommand(
    compiler: compiler,
    flags: flags,
    directory: runtimeDirectory,
    output: p.relative(
      p.join(outputDirectory, 'libtree-sitter.dylib'),
      from: runtimeDirectory,
    ),
    environment: environment,
  );
  final grammarCommands = [
    for (final build in builds)
      _grammarCommands(root, build, compiler, flags, environment),
  ];
  final commands = [runtime, for (final group in grammarCommands) ...group];
  File(
    p.join(root, 'build', 'compile_commands.json'),
  ).writeAsStringSync(encodeCompileCommands(commands));
  Directory(p.join(outputDirectory, 'dylibs')).createSync(recursive: true);
  for (final build in builds) {
    Directory(p.join(root, build.objectDirectory)).createSync(recursive: true);
    Directory(
      p.join(outputDirectory, build.dylibDirectory),
    ).createSync(recursive: true);
  }
  _requireNone(
    'compile',
    [
      ...await pooled([runtime], _run),
      ...await pooled(grammarCommands, _runInOrder),
    ].nonNulls.toList(),
  );

  _step('Checking every library');
  final expectations = [
    LibraryExpectation(
      path: p.join(outputDirectory, 'libtree-sitter.dylib'),
      installName: '@rpath/libtree-sitter.dylib',
      exportedSymbols: const ['_ts_parser_new', '_ts_language_abi_version'],
    ),
    for (final build in builds)
      LibraryExpectation(
        path: p.join(
          outputDirectory,
          build.dylibDirectory,
          build.dylibFileName,
        ),
        installName: '@rpath/${build.dylibFileName}',
        exportedSymbols: ['_tree_sitter_${build.symbol}'],
      ),
  ];
  _requireNone('libraries', [
    for (final problems in await pooled(
      expectations,
      (e) => libraryProblems(e, toolchain),
    ))
      ...problems,
  ]);

  _step('Writing query bundles, manifest.json and build_info.json');
  final manifest = _writeBundles(
    root,
    inputs,
    outputDirectory,
    entries,
    builds,
  );
  File(
    p.join(outputDirectory, 'manifest.json'),
  ).writeAsStringSync(encodeManifest(manifest));
  final info = buildInfo(
    release: release,
    toolchain: toolchain,
    compiler: compiler,
    flags: flags,
    grammarFlags: {
      for (final build in builds) build.name: _grammarFlagRecord(root, build),
    },
    repositoryCommit:
        commit ?? (await runGit(root, ['rev-parse', 'HEAD'])).trim(),
    repositoryDirty: (await runGit(root, [
      'status',
      '--porcelain',
    ])).trim().isNotEmpty,
    languageVersion: languageVersions.current,
    minCompatibleLanguageVersion: languageVersions.minCompatible,
    sources: sourceRecords,
    generated: generatedRecords,
    packingTools: await packingToolVersions(),
  );
  File(
    p.join(outputDirectory, 'build_info.json'),
  ).writeAsStringSync(encodeBuildInfo(info));

  _step('Checking the recorded flags and the manifest');
  await _checkRecords(root, outputDirectory, builds);

  _step('Checking the build through the runtime it ships');
  await _checkRelease(root, outputDirectory);
  if (commit != null) {
    await checkUnchangedSince(runGit, root, commit);
    print('  the working tree is still clean at $commit');
  }
  final output = Directory(outputDirectory).renameSync(p.join(root, 'output'));

  print(
    '\n✓ Built libtree-sitter.dylib, ${builds.length} grammar dylibs and '
    '${manifest.values.where((e) => e['queryOnly'] == true).length} '
    'query-only bundles into output/',
  );
  if (release != null && commit != null) {
    _step('Packing $release${dryRun ? ' (dry run)' : ''}');
    final archive = await _createReleaseArchive(
      root,
      output.path,
      commit,
      dryRun: dryRun,
    );
    print('  ${archive.path}\n  sha256 ${archive.sha256}');
    final notes = p.join(output.path, 'release-notes.md');
    File(notes).writeAsStringSync(releaseNotes(info, archive.sha256));
    print('  $notes');
    if (publish) {
      _step('Publishing $release to $releaseRepository');
      final assets = await _releaseAssets(output.path, archive, info);
      await publishRelease(
        tag: release,
        tagObject: (await runGit(root, [
          'rev-parse',
          '--verify',
          'refs/tags/$release',
        ])).trim(),
        commit: commit,
        assets: assets,
        notesFile: notes,
      );
      print(
        '  published ${assets.length} assets; GitHub reports the digest '
        'of each as the local sha256',
      );
    }
  }
}

/// [sources], the directory `--sources` names, as the file system spells
/// it, with every symbolic link resolved.
///
/// Throws a [BuildException] when it cannot be resolved, or when it is or
/// lies inside `build/` or `output/` under [root], which the build deletes.
/// Both sides are compared resolved, so neither a link nor another case of
/// the same name on a case-insensitive volume slips past.
String _sourcesDirectory(String root, String sources) {
  final String resolved;
  try {
    resolved = Directory(sources).resolveSymbolicLinksSync();
  } on FileSystemException catch (error) {
    throw BuildException(
      '--sources=$sources cannot be resolved: '
      '${error.osError?.message ?? error.message}',
    );
  }
  for (final owned in ['build', 'output']) {
    final directory = Directory(p.join(root, owned));
    if (!directory.existsSync()) continue;
    final canonical = directory.resolveSymbolicLinksSync();
    if (p.equals(resolved, canonical) || p.isWithin(canonical, resolved)) {
      throw BuildException(
        '--sources=$sources is inside $owned/, which the build deletes; '
        'keep the bundles elsewhere',
      );
    }
  }
  return resolved;
}

/// Runs the release preflight and returns the commit the release builds.
Future<String> _releaseCommit(
  String root,
  String release, {
  required bool dryRun,
}) async {
  _step('Checking that $release builds from a clean commit');
  final commit = await checkReleasePreflight(
    runGit,
    root,
    release,
    dryRun: dryRun,
  );
  if (dryRun) print('  --dry-run: not requiring HEAD to be the tag $release');
  return commit;
}

/// Extracts the tree of this repository's [commit] into `build/repository`
/// and returns that directory, from which a release reads the repository's
/// own files: its pins, query files, provenance and licences.
///
/// [extractCommit] checks every extracted file against its committed blob,
/// so an edit to the working tree while the build runs never reaches what
/// the build reads.
Future<String> _extractRepository(String root, String commit) async {
  final directory = p.join(root, 'build', 'repository');
  await extractCommit(root, commit, directory);
  print("  reading this repository's files at $commit, not the working tree");
  return directory;
}

void _step(String title) => print('\n── $title');

void _delete(String path) {
  if (Directory(path).existsSync()) Directory(path).deleteSync(recursive: true);
}

void _requireNone(String what, List<String> problems) {
  if (problems.isEmpty) return;
  throw BuildException(['$what:', ...problems].join('\n  '));
}

Iterable<Map<String, Object?>> _urlEntries(
  List<Map<String, Object?>> entries,
) => entries.where((entry) => entry['url'] is String);

/// Every problem with `tool/query_provenance.json` and with the header each
/// query file derived from nvim-treesitter carries.
List<String> _provenanceProblems(
  String root,
  List<Map<String, Object?>> entries,
) {
  final reading = readRepositoryProvenance(root);
  if (reading.problems.isNotEmpty) return reading.problems;
  return queryHeaderCheck(root, reading.entries, licenseLookup(entries));
}

/// Writes `THIRD_PARTY_NOTICES.md` into [outputDirectory] and requires the
/// committed copy at [root] to be the same text.
void _writeNotices(String root, String outputDirectory, NoticesInput input) {
  final notices = thirdPartyNotices(input);
  File(p.join(outputDirectory, noticesFileName))
    ..createSync(recursive: true)
    ..writeAsStringSync(notices);
  final committed = File(p.join(root, noticesFileName));
  if (!committed.existsSync() || committed.readAsStringSync() != notices) {
    throw BuildException(
      '$noticesFileName is not what the pinned sources, the query '
      'provenance and the licences produce; run '
      'dart run tool/write_notices.dart and commit it',
    );
  }
  print('  $noticesFileName is the committed text');
}

/// Requires the `tree-sitter` submodule's checkout to be the toolchain's
/// commit.
Future<void> _requireRuntimeSubmodule(String root, Toolchain toolchain) async {
  // Without its own .git, git would answer for this repository instead.
  if (FileSystemEntity.typeSync(p.join(root, 'tree-sitter', '.git')) ==
      FileSystemEntityType.notFound) {
    throw const BuildException(
      'the tree-sitter submodule is not checked out: run '
      'git submodule update --init, or build from a release\'s source '
      'bundles with --sources=<dir>',
    );
  }
  final head = (await runGit(p.join(root, 'tree-sitter'), [
    'rev-parse',
    'HEAD',
  ])).trim();
  if (head != toolchain.treeSitterCommit) {
    throw BuildException(
      'tree-sitter is checked out at $head; '
      'toolchain.json pins ${toolchain.treeSitterTag} '
      '(${toolchain.treeSitterCommit})',
    );
  }
}

/// The runtime's `TREE_SITTER_LANGUAGE_VERSION` and
/// `TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION`, after checking that its
/// Makefile declares the toolchain's version.
({int current, int minCompatible}) _runtimeLanguageVersions(
  String runtimeDirectory,
  Toolchain toolchain,
) {
  final makefile = File(
    p.join(runtimeDirectory, 'Makefile'),
  ).readAsStringSync();
  final version = RegExp(
    r'^VERSION := (\S+)$',
    multiLine: true,
  ).firstMatch(makefile)?.group(1);
  if (version != toolchain.runtimeVersion) {
    throw BuildException(
      'the runtime Makefile declares VERSION $version, '
      'toolchain.json says ${toolchain.runtimeVersion}',
    );
  }
  return apiLanguageVersions(
    File(
      p.join(runtimeDirectory, 'lib', 'include', 'tree_sitter', 'api.h'),
    ).readAsStringSync(),
  );
}

/// Generates each of [generated] with the pinned CLI into its
/// `build/gen/<name>`, at language ABI [abi], requires its files to have
/// the `generatedSha256` its entry records, and packs them into
/// [outputDirectory]'s `sources/`; returns what `build_info.json` records
/// of each bundle, by grammar.
Future<Map<String, Map<String, Object?>>> _generate(
  String root,
  Toolchain toolchain,
  List<GrammarBuild> generated,
  String outputDirectory,
  int abi,
) async {
  if (generated.isEmpty) return const {};
  _step(
    'Generating ${generated.map((b) => b.name).join(', ')} with '
    'tree-sitter ${toolchain.cliVersion}',
  );
  final cli = await ensureCli(root, toolchain);
  final records = <String, Map<String, Object?>>{};
  for (final build in generated) {
    final directory = p.join(root, build.generatedDirectory);
    await generateParser(
      cli: cli,
      grammarDirectory: p.join(root, p.dirname(build.sourceDirectory)),
      outputDirectory: directory,
      abi: abi,
    );
    await requireGenerated(
      build,
      directory,
      'if the pin is right, record its digest with '
      'dart run tool/pin_grammars.dart --record-files',
    );
    final file = p.posix.join(
      sourcesDirectoryName,
      generatedBundleName(build.name, build.commit),
    );
    final bundle = p.join(outputDirectory, file);
    await packGenerated(directory, bundle);
    records[build.name] = generatedRecord(
      build,
      toolchain,
      file,
      await fileSha256(bundle),
    );
  }
  print('  each generated tree has the generatedSha256 its pin records');
  return records;
}

/// Takes the generated sources of each of [generated] from [bundles], a
/// release's downloaded assets, instead of running the CLI: each bundle
/// must have the sha256 the `build_info.json` there records, and its files
/// the `generatedSha256` its entry records. Copies each bundle into
/// [outputDirectory]'s `sources/`, unpacks it into `build/gen/<name>` and
/// returns what `build_info.json` records of it, by grammar.
Future<Map<String, Map<String, Object?>>> _takeGenerated(
  String root,
  Toolchain toolchain,
  List<GrammarBuild> generated,
  String outputDirectory,
  String bundles,
) async {
  if (generated.isEmpty) return const {};
  _step(
    'Taking the generated sources of '
    '${generated.map((b) => b.name).join(', ')} from $bundles',
  );
  final info = File(p.join(bundles, 'build_info.json'));
  final recorded = (jsonDecode(info.readAsStringSync()) as Map)['generated'];
  if (recorded is! Map<String, Object?>) {
    throw BuildException('${info.path} records no generated sources');
  }
  final records = <String, Map<String, Object?>>{};
  for (final build in generated) {
    final sha256 = await checkRecordedGenerated(bundles, build, recorded);
    final file = p.posix.join(
      sourcesDirectoryName,
      generatedBundleName(build.name, build.commit),
    );
    final bundle = p.join(outputDirectory, file);
    File(p.join(bundles, p.basename(file))).copySync(bundle);
    final directory = p.join(root, build.generatedDirectory);
    await unpackBundle(bundle, directory);
    await requireGenerated(
      build,
      directory,
      'the bundle is not what the pinned CLI generates for the pin',
    );
    records[build.name] = generatedRecord(build, toolchain, file, sha256);
  }
  print('  each generated tree has the generatedSha256 its pin records');
  return records;
}

/// Each source [build] compiles, with the directory its headers come
/// from: its `parser.c` and, where it has one, its `scanner.c`.
List<(String, String)> _grammarSources(String root, GrammarBuild build) => [
  (build.parserSource, build.parserIncludeDirectory),
  if (scannerSource(root, build) case final scanner?)
    (scanner, scannerIncludeDirectory(root, build)),
];

/// The flags each of [build]'s invocations passes beyond the shared lists,
/// as `build_info.json` records them: each source's, by file name, and the
/// link's under `link`.
Map<String, List<String>> _grammarFlagRecord(String root, GrammarBuild build) =>
    {
      for (final (source, include) in _grammarSources(root, build))
        p.basename(source): grammarSourceFlags(include),
      'link': grammarLinkFlags(build.name),
    };

/// The compile of each of [build]'s sources, then its link, in order.
List<CompileCommand> _grammarCommands(
  String root,
  GrammarBuild build,
  Compiler compiler,
  BuildFlags flags,
  Map<String, String> environment,
) {
  final sources = _grammarSources(root, build);
  final compiles = [
    for (final (source, include) in sources)
      grammarCompileCommand(
        compiler: compiler,
        flags: flags,
        directory: root,
        includeDirectory: include,
        source: source,
        object: p.join(
          build.objectDirectory,
          '${p.basenameWithoutExtension(source)}.o',
        ),
        environment: environment,
      ),
  ];
  return [
    ...compiles,
    grammarLinkCommand(
      compiler: compiler,
      flags: flags,
      directory: root,
      libraryName: build.name,
      objects: [for (final compile in compiles) compile.output],
      output: p.join('build', 'out', build.dylibDirectory, build.dylibFileName),
      environment: environment,
    ),
  ];
}

Future<String?> _run(CompileCommand command) async {
  try {
    await runCompileCommand(command);
    return null;
  } on CompilerException catch (error) {
    return error.message;
  }
}

Future<String?> _runInOrder(List<CompileCommand> commands) async {
  for (final command in commands) {
    if (await _run(command) case final problem?) return problem;
  }
  return null;
}

/// Bundles every language's queries, read from `queries/` under [inputs],
/// into [outputDirectory] and returns the manifest, in `grammars.json`
/// order; each grammar's parser is read from its build under [root].
Map<String, Map<String, Object?>> _writeBundles(
  String root,
  String inputs,
  String outputDirectory,
  List<Map<String, Object?>> entries,
  List<GrammarBuild> builds,
) {
  final manifest = <String, Map<String, Object?>>{};
  for (final entry in entries) {
    if (entry['noop'] == true) {
      manifest[entry['name']! as String] = noopEntry(entry);
    } else if (entry['queryOnly'] == true) {
      final name = entry['name']! as String;
      final manifestEntry = queryOnlyEntry(entry);
      bundleQueries(
        inputs,
        name,
        manifestEntry['queries']! as Map<String, Object?>,
        p.join(outputDirectory, 'queries', name),
      );
      manifest[name] = manifestEntry;
    } else {
      for (final build in builds.where((build) => build.entry == entry)) {
        final manifestEntry = grammarEntry(
          inputs,
          build,
          parserAbi(p.join(root, build.parserSource)),
        );
        bundleQueries(
          inputs,
          build.name,
          manifestEntry['queries']! as Map<String, Object?>,
          p.join(outputDirectory, build.dylibDirectory),
        );
        manifest[build.name] = manifestEntry;
      }
    }
  }
  return manifest;
}

/// Reads `build_info.json` in [outputDirectory] and
/// `build/compile_commands.json` back from disk and requires every
/// invocation to have passed exactly the recorded flags; then requires
/// `validate_manifest.dart` to pass on [outputDirectory]'s manifest.
Future<void> _checkRecords(
  String root,
  String outputDirectory,
  List<GrammarBuild> builds,
) async {
  final problems = checkRecordedFlags(
    buildInfoPath: p.join(outputDirectory, 'build_info.json'),
    compileCommandsPath: p.join(root, 'build', 'compile_commands.json'),
    grammarNames: {for (final build in builds) build.name},
  );
  _requireNone('recorded flags', problems);
  print('  every compiler invocation passed exactly the recorded flags');
  final validation = await Process.run(Platform.resolvedExecutable, [
    'run',
    p.join('tool', 'validate_manifest.dart'),
    p.join(outputDirectory, 'manifest.json'),
  ], workingDirectory: root);
  if (validation.exitCode != 0) {
    throw BuildException(
      'validate_manifest.dart exited '
      '${validation.exitCode}\n${validation.stdout}${validation.stderr}',
    );
  }
  print('  validate_manifest.dart passed');
}

/// Requires `tool/check_release.dart` to pass on [outputDirectory], in a
/// process of its own because it loads every library it checks.
Future<void> _checkRelease(String root, String outputDirectory) async {
  final result = await Process.run(Platform.resolvedExecutable, [
    'run',
    p.join('tool', 'check_release.dart'),
    outputDirectory,
  ], workingDirectory: root);
  for (final line in '${result.stdout}'.trim().split('\n')) {
    print('  $line');
  }
  if (result.exitCode != 0) {
    throw BuildException(
      'check_release.dart exited ${result.exitCode}\n${result.stderr}',
    );
  }
}

/// Every file a release attaches, mapped to its sha256: the archive, its
/// `.sha256`, `build_info.json`, every source bundle and every bundle of
/// generated sources.
Future<Map<String, String>> _releaseAssets(
  String outputDirectory,
  ({String path, String sha256}) archive,
  Map<String, Object?> info,
) async {
  final sidecar = '${archive.path}.sha256';
  final buildInfo = p.join(outputDirectory, 'build_info.json');
  return {
    archive.path: archive.sha256,
    sidecar: await fileSha256(sidecar),
    buildInfo: await fileSha256(buildInfo),
    for (final records in [info['sources']! as Map, info['generated']! as Map])
      for (final record in records.values)
        p.join(outputDirectory, (record as Map)['file'] as String):
            record['sha256'] as String,
  };
}

/// Packs `output/` into [releaseArchiveName], or into [dryRunArchiveName]
/// when [dryRun], and writes its sha256 beside it; returns the archive's
/// path and sha256.
///
/// Every file is given mode 0644 (0755 for a dylib and a directory) and
/// the time of [commit], the commit built, first, so the same build packs
/// to the same bytes.
Future<({String path, String sha256})> _createReleaseArchive(
  String root,
  String outputDirectory,
  String commit, {
  required bool dryRun,
}) async {
  final archive = p.join(
    outputDirectory,
    dryRun ? dryRunArchiveName : releaseArchiveName,
  );
  final epoch = int.parse(
    (await runGit(root, ['log', '-1', '--format=%ct', commit])).trim(),
  );
  final files = archiveFiles(outputDirectory);
  await normalizeArchiveFiles(outputDirectory, files, epoch);
  await packArchive(outputDirectory, files, archive);
  final sha256 = await fileSha256(archive);
  File(
    '$archive.sha256',
  ).writeAsStringSync('$sha256  ${p.basename(archive)}\n');
  return (path: archive, sha256: sha256);
}
