; Removed (if_statement), (if_expression), (else_clause), (if_type_expression) - fold block instead to keep else visible
[
  (block)
  (switch_expression)
  (initializer_list)
  (asm_expression)
  (multiline_string)
  (while_statement)
  (for_statement)
  (for_expression)
  (while_expression)
  (function_signature)
  (parameters)
  (call_expression)
  (struct_declaration)
  (opaque_declaration)
  (enum_declaration)
  (union_declaration)
  (error_set_declaration)
] @fold
